language: node_js
node_js:
- '8'
dist: trusty
before_install: |
  set -e
  date
  npm install -g lerna
  lerna bootstrap
  date
install: |
  set -e
  date
  lerna bootstrap 2>&1
  date
script: 'lerna run test 2>&1'
after_failure: 'tail -n +1 -- /home/travis/.npm/_logs/*-debug.log'
deploy: |
  lerna publish --yes --conventional-commits -m "chore(release): publish %s"
cache:
  directories:
  - node_modules
services: 
