language: node_js
node_js:
- '8'
dist: trusty
before_install: |
  set -e
  date
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  npm install -g
  npm install -g lerna
  lerna bootstrap
  date
install: |
  set -e
  date
  lerna bootstrap 2>&1
  date
script: lerna run test 2>&1
after_failure: tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
deploy:
  - provider: script
    script: "./.travis/unstable.sh ${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./.travis/stable.sh ${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      branch: master
      tags: true
cache:
  directories:
  - node_modules
services: 
