# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN_TEST: ${{ secrets.NPM_TOKEN_TEST }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: build and publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_TEST }}" > .npmrc
          npx lerna bootstrap
          npm run pkgset ${{ github.event.release.tag_name }}
          npx lerna exec -- npm publish --tag="unstable" 2>&1

      - name: create PR to increment version
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          commit-message: 'chore(actions): publish ${{ github.event.release.tag_name }} to npm'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: cicero-publish-${{ github.event.release.tag_name }}
          delete-branch: true
          title: 'chore(actions): publish ${{ github.event.release.tag_name }} to npm'
          body: |
            # NPM Publish

            Publish build to NPM
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false